import json
p=json.load(open("data/prices.json"))
meta={
 "NVDA":{"name":"Nvidia","sym":"NVDA","buyLabel":"Apr 2020","color":"#7C5CFF"},
 "SPCX":{"name":"SpaceX","sym":"SPCX","buyLabel":"May 2023","color":"#B79CFF"},
 "^GSPC":{"name":"S&P 500","sym":"SPX","buyLabel":"Apr 2018","color":"#F2C94C"},
 "AAPL":{"name":"Apple","sym":"AAPL","buyLabel":"Jul 2023","color":"#F2A65A"},
}
hold=[]
for k in ["NVDA","SPCX","^GSPC","AAPL"]:
    d=p[k]; m=meta[k]
    hold.append({**m,"buyDate":d["buy_date"],"buyPrice":d["buy"],"invested":1000,"weekly":d["weekly"],"daily":d["daily"],"estUntil":d.get("est_until"),"note":d.get("note")})
open("data.js","w").write("// Generated by data/build.py from data/prices.json\nconst HOLDINGS = "+json.dumps(hold)+";\nconst AS_OF = \""+p["NVDA"]["last_date"]+"\";\n")
print("wrote data.js")
