import json
p=json.load(open("data/prices.json"))
an=json.load(open("data/analysts.json")) if __import__("os").path.exists("data/analysts.json") else {}
meta={
 "NVDA":{"name":"Nvidia","sym":"NVDA","buyLabel":"Apr 2020","color":"#7C5CFF"},
 "SPCX":{"name":"SpaceX","sym":"SPCX","buyLabel":"May 2023","color":"#B79CFF"},
 "^GSPC":{"name":"S&P 500","sym":"SPX","buyLabel":"Apr 2018","color":"#F2C94C","index":True},
 "AAPL":{"name":"Apple","sym":"AAPL","buyLabel":"Jul 2023","color":"#F2A65A"},
}
hold=[]
for k in ["NVDA","SPCX","^GSPC","AAPL"]:
    d=p[k]; m=meta[k]; a=an.get(k,{})
    hold.append({**m,
      "lots":[{"date":d["buy_date"],"price":d["buy"],"amount":1000}],
      "weekly":d["weekly"],"daily":d["daily"],"estUntil":d.get("est_until"),"note":d.get("note"),
      "analysts":{"low":a.get("targetLowPrice"),"mean":a.get("targetMeanPrice"),"high":a.get("targetHighPrice"),
                  "n":a.get("numberOfAnalystOpinions"),"rec":a.get("recommendationKey"),"beta":a.get("beta"),
                  "sector":a.get("sector"),"industry":a.get("industry"),"fwdPE":a.get("forwardPE"),
                  "wkLow":a.get("fiftyTwoWeekLow"),"wkHigh":a.get("fiftyTwoWeekHigh")}})
open("data.js","w").write("// Generated by data/build.py from data/prices.json + data/analysts.json\nconst HOLDINGS = "+json.dumps(hold)+";\nconst AS_OF = \""+p["NVDA"]["last_date"]+"\";\n")
print("wrote data.js", [(h["sym"],h["analysts"]["mean"]) for h in hold])
